// Generated by Selenium IDE
package com.orhrm.tests;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import com.orhrm.base.BaseTest;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginTest extends BaseTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeMethod
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterClass
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void login() {
    driver.get("https://tutorialsninja.com/demo/index.php?");
    driver.manage().window().setSize(new Dimension(1280, 672));
    driver.findElement(By.cssSelector(".dropdown .hidden-xs")).click();
    driver.findElement(By.linkText("Register")).click();
    driver.findElement(By.id("input-firstname")).click();
    driver.findElement(By.id("input-firstname")).sendKeys("afgafs");
    driver.findElement(By.id("input-lastname")).click();
    driver.findElement(By.id("input-lastname")).sendKeys("shevd");
    driver.findElement(By.id("input-email")).click();
    driver.findElement(By.id("input-email")).sendKeys("gsveudv@gmail.com");
    driver.findElement(By.id("input-telephone")).click();
    driver.findElement(By.id("input-telephone")).sendKeys("5363778899");
    driver.findElement(By.id("input-password")).click();
    driver.findElement(By.id("input-password")).sendKeys("Rajat@#$");
    driver.findElement(By.id("input-confirm")).click();
    driver.findElement(By.id("input-confirm")).sendKeys("Rajat@#$");
    driver.findElement(By.name("agree")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();
    extent.flush();
    
  }
}

